services:
  contiki:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - "./src:/home/user/src"

# macOS: docker compose up
# Linux: docker compose -f docker-compose.linux.yml up
